version: 0.0
os: linux

files:
  - source: /
    destination: /home/tht-api-admin/deploy
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/tht-api-admin/deploy/
    owner: tht-api-admin
    group: tht-api-admin

hooks:
  AfterInstall:
    - location: /start_server.sh
      timeout: 60
      runas: tht-api-admin
