spring:
  application:
    name: infra
  config:
    import: security/Server-Security/application-security.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true