spring:
    config:
        import: security/application-security.yaml
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
#        show-sql: true

    thymeleaf:
        prefix: classpath:static/
        suffix: .html
        cache: false

springdoc:
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
        url: /docs/open-api-3.0.1.json
        path: /docs/swagger

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
