spring:
    config:
        import: security/application-security.yaml
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    thymeleaf:
        prefix: classpath:static/
        suffix: .html
        cache: false