spring:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:  jdbc:mysql://tht-api-test-db.cwf29l5ktryb.ap-northeast-2.rds.amazonaws.com:3306/tht_test?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: thtdbmaster!!

    data:
        mongodb:
            host: ec2-13-124-194-236.ap-northeast-2.compute.amazonaws.com
            port: 27017
            authentication-database: admin
            username: tht_chat_db
            password: thtrkqhwkrh~!
            database: chat_db

aligo:
    api-key : ckuo7x3g4vzvcady6efjac4rmrn5pqro
    user-id : tht221202
    sender : 01042469529

jwt:
    secret-key : "thtTalkAppJwtTokenSecretKeyLetsGoSuperAppSuperPowerNumberOneTalkApp"

kakao:
    rest-api-key : 797d453cde7765536711ad81d3acbdbd
    admin-key : 45a84e08083847bbcc01eb3658db7704
